[project]
name = "ojs_scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Miguel González Duque", email = "miguelgondu@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.0.0",
    "supabase>=2.15.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
